apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: wordpress-mysql
    qcloud-app: wordpress-mysql
  name: wordpress-mysql
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: wordpress-mysql
    qcloud-app: wordpress-mysql
  sessionAffinity: None
  type: LoadBalancer
