apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: ${lb-subnet}
    service.kubernetes.io/qcloud-share-existed-lb: "true"
    service.kubernetes.io/tke-existed-lbid: ${lb-id}
    service.cloud.tencent.com/tke-service-config: ${service-lb-config-name}
  labels:
    k8s-app: wordpress-mysql
    qcloud-app: wordpress-mysql
  name: ${service-lb-name}
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: wordpress-mysql
    qcloud-app: wordpress-mysql
  sessionAffinity: None
  type: LoadBalancer
