apiVersion: cloud.tencent.com/v1alpha1
kind: TkeServiceConfig
metadata:
   name: ${service-lb-config-name}
   namespace: default
spec:
   loadBalancer:
     l4Listeners:
     - protocol: TCP
       port: 80
       session:
         enable: true
         sessionExpireTime: 3600
